'use client';

// import type { Metadata } from "next";
import { Montserrat } from 'next/font/google';

import StyledComponentsRegistry from './registry';
import GlobalStyles from './styles/global';
import theme from './styles/theme';

import { ThemeProvider } from 'styled-components';

const montserrat = Montserrat({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <StyledComponentsRegistry>
          <GlobalStyles />
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
