'use client';

// import type { Metadata } from "next";
import { Montserrat } from 'next/font/google';

import { ThemeProvider } from 'styled-components';

import { queryClient } from '@/lib/react-query';
import { QueryClientProvider } from '@tanstack/react-query';

import GlobalStyles from '../styles/global';
import theme from '../styles/theme';
import StyledComponentsRegistry from './registry';

const montserrat = Montserrat({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <QueryClientProvider client={queryClient}>
          <StyledComponentsRegistry>
            <ThemeProvider theme={theme}>
              <GlobalStyles />
              {children}
            </ThemeProvider>
          </StyledComponentsRegistry>
        </QueryClientProvider>
      </body>
    </html>
  );
}
